### ISSUE TITLE
[Bug]: Invalid client credentials

### ISSUE THREAD

**Issue by 0xjvict** [elisei/getnet-payment-magento#26]
### Detalhes de contato

jvictor.express2@gmail.com

### O que aconteceu?

Foi feita a instalação do módulo utilizando o composer(também testei manualmente) e após todas as etapas de instalação e configuração das credenciais, eu habilitei apenas o boleto para testar e está dando erro ao tentar finalizar o pedido.

### Versão do Magento

2.3.x (Magento >= 2.3.0 e < 2.4.0)

### O problema pode ter alguma relação com um navegador específico?

Não tem relação com o navegador usado

### Há logs relavantes sobre o problema?

```shell
#### Corpo da requisição

{
  "cartId": "53",
  "billingAddress": {
    "countryId": "BR",
    "regionId": "489",
    "regionCode": "BA",
    "region": "Bahia",
    "street": [
      "Rua Lisboa",
      "123",
      "Monte Castelo"
    ],
    "company": "",
    "telephone": "(73) 3826-0527",
    "postcode": "45990-093",
    "city": "Teixeira de Freitas",
    "firstname": "Luan Manuel",
    "lastname": "Renato Duarte",
    "saveInAddressBook": null,
    "extension_attributes": {}
  },
  "paymentMethod": {
    "method": "getnet_paymentmagento_boleto",
    "additional_data": {
      "boleto_payer_fullname": "joao victor",
      "boleto_payer_tax_document": "845.165.749-42"
    }
  }
}

#### Reposta da requisição

message :"A Transação foi recusada. Por favor tente novamente mais tarde."

trace :"#0 /home/tipotenis/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(53, Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address))\n#1 /home/tipotenis/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callParent('savePaymentInfo...', Array)\n#2 /home/tipo…erceptor->___callPlugins('dispatch', Array, Array)\n#11 /home/tipotenis/public_html/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 /home/tipotenis/public_html/vendor/magento/framework/App/Bootstrap.php(261): Magento\\Framework\\App\\Http->launch()\n#13 /home/tipotenis/public_html/pub/index.php(40): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#14 {main}"

#### var/log/payment.log

[2022-06-28 19:27:22] main.DEBUG: array (
  'url' => 'https://api-sandbox.getnet.com.br/v1/payments/boleto',
  'request' => '{"seller_id":"f1f39b74-5db0-4e16-a82a-26da9f0fdc3d","amount":31000,"currency":"BRL","order":{">
  'response' => '{
    "message": "Unauthorized",
    "name": "GatewayAuthenticationOAuth2ServiceError",
    "status_code": 401,
    "details": [
        {
            "status": "DENIED",
            "error_code": "AUTHENTICATION-401",
            "description": "Unauthorized",
            "description_detail": "Invalid client credentials"
        }
    ]
}',
```

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Eu não consegui configurar o módulo

**Comment by elisei** [comment]
Oi @0xjvict tudo bem?

Por favor rode na bin do magento o comando:

`bin/magento getnet:basic:refresh`

E me envia por favor log do que sair!

O seu erro está relacionado ao token de uso da Getnet, o comando acima irá tentar criar esse token, e vai trazer informações sobre esse processo.

**Comment by 0xjvict** [comment]
> Oi @0xjvict tudo bem?
> 
> Por favor rode na bin do magento o comando:
> 
> `bin/magento getnet:basic:refresh`
> 
> E me envia por favor log do que sair!
> 
> O seu erro está relacionado ao token de uso da Getnet, o comando acima irá tentar criar esse token, e vai trazer informações sobre esse processo.

Resolvido @elisei , obrigado pela ajuda.
